version: '3.9'

services:
    db:
      image: postgres
      ports:
        - "5432:5432"
      volumes:
        - ./data:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=zaq1@WSX
        - POSTGRES_USER=mygym
        - POSTGRES_DB=gym